inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/PerlBackrefs:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
